Import Upstream version 3.28.1

diff --git a/dbld/rules b/dbld/rules
--- a/dbld/rules
+++ b/dbld/rules
@@ -1,26 +1,50 @@
 #!/usr/bin/make -f
 
-BUILDER_IMAGES=centos-6 centos-7 debian-jessie debian-stretch debian-buster ubuntu-xenial ubuntu-trusty ubuntu-cosmic ubuntu-bionic
+BUILDER_IMAGES=		\
+	centos-6 	\
+	centos-7 	\
+	fedora-32	\
+	debian-stretch	\
+	debian-buster	\
+	debian-sid	\
+	ubuntu-xenial	\
+	ubuntu-bionic \
+	ubuntu-focal \
+	kira
+
 IMAGES=${BUILDER_IMAGES} devshell
 DEFAULT_IMAGE ?= ubuntu-bionic
+TARBALL_IMAGE ?= ubuntu-bionic
 DEFAULT_DEB_IMAGE=$(DEFAULT_IMAGE)
 DEFAULT_RPM_IMAGE=centos-7
 DOCKER=docker
+MODE ?= snapshot
+VERSION=$(shell MODE=${MODE} scripts/version.sh)
 DOCKER_RUN_ARGS=-e USER_NAME_ON_HOST=$(shell whoami)	\
         --network=host --privileged \
 	--ulimit nofile=1024:1024 \
 	-v $(ROOT_DIR):/source \
+        -v $(DBLD_DIR):/dbld \
 	-v $(DBLD_DIR)/build:/build \
 	-v $(DBLD_DIR)/install:/install \
+	-e CONFIGURE_OPTS="$${CONFIGURE_OPTS:-$(CONFIGURE_OPTS)}" \
+	-e CCACHE_DIR=/build/ccache \
+	-e MODE=$(MODE) \
+	-e VERSION=$(VERSION) \
+	-e PATH=/usr/lib/ccache:/usr/lib64/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
+	-e GRADLE_USER_HOME=/build/gradle-home \
+	-e GRADLE_PROJECT_CACHE_DIR=/build/gradle-cache \
+	-e GRADLE_FLAGS=--build-cache \
 	$(if $(wildcard ${HOME}/.gitconfig),-v ${HOME}/.gitconfig:${HOME}/.gitconfig)
+DOCKER_BUILD_ARGS=
 ROOT_DIR=$(shell pwd)
 DBLD_DIR=$(ROOT_DIR)/dbld
 BUILD_DIR=$(DBLD_DIR)/build
 RELEASE_DIR=$(DBLD_DIR)/release
-VERSION=$(shell cat VERSION)
 TARBALL=$(BUILD_DIR)/syslog-ng-$(VERSION).tar.gz
-MODE=snapshot
-CONFIGURE_OPTS=--enable-debug --enable-manpages --with-python=2 --prefix=/install --with-docbook=/usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl $(CONFIGURE_ADD)
+CONFIGURE_OPTS=--enable-debug --enable-manpages --with-python=2 --prefix=/install $(CONFIGURE_ADD)
+
+DOCKER_SHELL=$(DOCKER) run $(DOCKER_RUN_ARGS) --rm -ti balabit/syslog-ng-$* /dbld/shell
 
 -include dbld/rules.conf
 
@@ -57,38 +81,48 @@ help:
 	@echo "Notable Make variables:"
 	@echo "  CONFIGURE_ADD -- add this to the configure command line in bootstrap"
 	@echo "  DEFAULT_IMAGE -- override the default image, currently $(DEFAULT_IMAGE)"
+	@echo "  TARBALL_IMAGE -- override the default image where the tarball is generated, currently $(TARBALL_IMAGE)"
 	@echo ""
 
 bootstrap: bootstrap-$(DEFAULT_IMAGE)
 bootstrap-%: setup
-	$(DOCKER) run $(DOCKER_RUN_ARGS) --rm -e CONFIGURE_OPTS="$${CONFIGURE_OPTS:-$(CONFIGURE_OPTS)}" -i  balabit/syslog-ng-$* /source/dbld/bootstrap
+	$(DOCKER) run $(DOCKER_RUN_ARGS) --rm  -i  balabit/syslog-ng-$* /dbld/bootstrap
 
 make-%: setup
-	$(DOCKER) run $(DOCKER_RUN_ARGS) --rm -i  balabit/syslog-ng-$(DEFAULT_IMAGE) /source/dbld/make $(MAKE_ARGS) $*
+	$(DOCKER) run $(DOCKER_RUN_ARGS) --rm -i  balabit/syslog-ng-$(DEFAULT_IMAGE) /dbld/make $(MAKE_ARGS) $*
 
-tarball: tarball-$(DEFAULT_IMAGE)
+tarball: tarball-$(TARBALL_IMAGE)
 tarball-%: setup
-	if [ -f $(TARBALL) ]; then \
-		count=`find $(ROOT_DIR) -newer $(TARBALL) | grep -v "^$(ROOT_DIR)/dbld/" | wc -l`; \
+	@if [ -f $(TARBALL) ]; then \
+		count=`find $(ROOT_DIR) -newer $(TARBALL) | sed -e 's,^$(ROOT_DIR),,' | grep -v -f $(DBLD_DIR)/tarball-changes.ignore | tee $(BUILD_DIR)/tarball-changed-files.txt | wc -l`; \
 	else \
+		echo "Tarball $(TARBALL) not found" > $(BUILD_DIR)/tarball-changed-files.txt; \
 		count=1; \
 	fi; \
-	[ "$${count}" -gt 0 ] && $(DOCKER) run $(DOCKER_RUN_ARGS) --rm -i balabit/syslog-ng-$* /source/dbld/tarball || true
+	if [ "$${count}" -gt 0 ]; then \
+		echo "Rebuilding, because these contents have changed since the tarball" && \
+		cat $(BUILD_DIR)/tarball-changed-files.txt && \
+		echo "Git status follows:" && \
+		git status && \
+		$(DOCKER) run $(DOCKER_RUN_ARGS) --rm -i balabit/syslog-ng-$* /dbld/tarball; \
+	fi
 
 
-pkg-tarball: pkg-tarball-$(DEFAULT_IMAGE)
+pkg-tarball: pkg-tarball-$(TARBALL_IMAGE)
 pkg-tarball-%: tarball-%
-	$(DOCKER) run $(DOCKER_RUN_ARGS) --rm -i balabit/syslog-ng-$* /source/dbld/pkg-tarball $(MODE)
+	$(DOCKER) run $(DOCKER_RUN_ARGS) --rm -i balabit/syslog-ng-$* /dbld/pkg-tarball $(MODE)
 
+package: package-$(DEFAULT_IMAGE)
+package-%: pkg-tarball
+	$(DOCKER) run $(DOCKER_RUN_ARGS) --rm -i  balabit/syslog-ng-$* /dbld/package
 
 deb: deb-$(DEFAULT_DEB_IMAGE)
-deb-%: pkg-tarball-%
-	$(DOCKER) run $(DOCKER_RUN_ARGS) --rm -i  balabit/syslog-ng-$* /source/dbld/deb
-
+deb-%: pkg-tarball
+	$(DOCKER) run $(DOCKER_RUN_ARGS) --rm -i  balabit/syslog-ng-$* /dbld/deb
 
 rpm: rpm-$(DEFAULT_RPM_IMAGE)
-rpm-%: pkg-tarball-$(DEFAULT_IMAGE)
-	$(DOCKER) run $(DOCKER_RUN_ARGS) --rm -i  balabit/syslog-ng-$* /source/dbld/rpm
+rpm-%: pkg-tarball
+	$(DOCKER) run $(DOCKER_RUN_ARGS) --rm -i  balabit/syslog-ng-$* /dbld/rpm
 
 
 release: MODE=release
@@ -97,15 +131,51 @@ release: deb
 clean:
 	rm -rf $(BUILD_DIR)/*
 
+run: run-$(DEFAULT_IMAGE)
+run: RUN_COMMAND=echo Specify RUN_COMMAND to do something sensible here
+run-%: setup
+	$(DOCKER) run $(DOCKER_RUN_ARGS) --rm -ti balabit/syslog-ng-$* bash -c "$(RUN_COMMAND)"
+
 shell: shell-$(DEFAULT_IMAGE)
 shell-%: setup
-	$(DOCKER) run $(DOCKER_RUN_ARGS) --rm -ti balabit/syslog-ng-$* /source/dbld/shell
+	$(DOCKER_SHELL)
 
 
 images: $(foreach image,$(IMAGES), image-$(image))
 image: image-$(DEFAULT_IMAGE)
+image-kira: image-ubuntu-bionic
+image-devshell: image-ubuntu-focal
 image-%:
-	cd $(DBLD_DIR)/images/ && $(DOCKER) build --network=host -t balabit/syslog-ng-$* -f $*.dockerfile .
+	$(DBLD_DIR)/prepare-image-build $* && \
+        $(DOCKER) build $(DOCKER_BUILD_ARGS) --build-arg=OS_PLATFORM=$* --build-arg=COMMIT=$$(git rev-parse --short HEAD) --network=host -t balabit/syslog-ng-$* -f $(DBLD_DIR)/images/$*.dockerfile $(DBLD_DIR)
+
+pull-images: $(foreach image,$(BUILDER_IMAGES), pull-image-$(image))
+pull-image: pull-image-$(DEFAULT_IMAGE)
+pull-image-%:
+	$(DOCKER) pull balabit/syslog-ng-$*
+
+cache-image-%:
+	IMAGE=$$(docker images -q balabit/syslog-ng-$*:latest | head -1);						\
+	if [ "$$IMAGE" = "" ]; then 											\
+		$(MAKE) -f $(DBLD_DIR)/rules pull-image-$*;								\
+	fi;														\
+	IMAGE=$$(docker images -q balabit/syslog-ng-$*:latest | head -1);						\
+	if [ "$$IMAGE" != "" ]; then 											\
+		image_commit=$$(docker inspect  --format '{{ index .Config.Labels "COMMIT"}}' $$IMAGE);			\
+		dbld_changes=$$( 											\
+			(git cat-file -e $${image_commit:-NO_COMMIT_LABEL_IN_DBLD_IMAGE}^{commit} 			\
+				&& git diff $${image_commit} -- dbld | wc -l						\
+				|| echo 1)										\
+		);													\
+	else														\
+		dbld_changes=1; 											\
+	fi;														\
+	if [ "$${dbld_changes}" -gt 0 ]; then									\
+		echo "$IMAGE: triggering rebuild, as dbld directory changed since the build of the image, or the cached image has no COMMIT label, or couldn't fetch from dockerhub" &&	\
+		$(MAKE) -f $(DBLD_DIR)/rules image-$*;									\
+	else 														\
+		echo "DBLD version in image matches, not initiating rebuild...";					\
+	fi
 
 exec: exec-$(DEFAULT_IMAGE)
 exec: EXEC_COMMAND=echo Specify EXEC_COMMAND to do something sensible here
@@ -114,7 +184,7 @@ exec-%: setup
 	$(DOCKER) exec -ti  $$container $(EXEC_COMMAND)
 
 login: login-$(DEFAULT_IMAGE)
-login-%: EXEC_COMMAND=gosu $(shell whoami) /source/dbld/shell
+login-%: EXEC_COMMAND=gosu $(shell whoami) /dbld/shell
 login-%: exec-%
 	@true
 
